### ISSUE TITLE
Problem with setup

### ISSUE THREAD

**Issue by SvatoYAngeL** [KarlOfDuty/SCPDiscord#194]
```[2024-12-30 14:39:39] [BOT]  [Info] Starting SCPDiscord version 3.2.3 (cb85aef)...
[2024-12-30 14:39:39] [BOT]  [Info] Loading config "C:\Users\Administrator\Desktop\DS_BOT\7779\config.yml"
[2024-12-30 14:39:39] [BOT]  [Info] Setting up Discord client...
[2024-12-30 14:39:43] [BOT]  [Info] Connecting to Discord...
[2024-12-30 14:39:45] [API]  [Info] DSharpPlus; version 5.0.0-nightly-02405+1a1932ec5983e04b81b958c26b21737782ffcb2b
[2024-12-30 14:39:46] [API]  [Info] No application command changes detected.
[2024-12-30 14:39:46] [API]  [Info] Registered 17 top-level slash commands, 17 total slash commands.
```

https://github.com/user-attachments/assets/ec81094f-5698-4cc7-a45c-57a19dac8a50

**This is given to me by the program "SCPDiscordBot_Windows_SC" after entering the discord server id in config
What to do?**

**Comment by KarlOfDuty** [comment]
Could you run the bot without shutting the terminal down? It's a bit hard to see the error if you don't.

**Comment by SvatoYAngeL** [comment]
> Можете ли вы запустить бота, не выключая терминал? Если вы этого не сделаете, то будет сложно увидеть ошибку
I didn't close it, after this error the program crashes

**Comment by KarlOfDuty** [comment]
The bot shutting down will not cause the terminal to shut down unless you start the terminal with the application as input.

Start the terminal first, then run the bot application in it.

**Comment by SvatoYAngeL** [comment]
Everything worked out, but a new problem arose.:
```
Unhandled exception. System.InvalidOperationException: Bots cannot use a custom status.
   at DSharpPlus.Entities.DiscordActivity..ctor(String name, ActivityType type)
   at SCPDiscord.DiscordAPI.SetActivity(String activityText, ActivityType activityType, UserStatus status) in /var/lib/jenkins/workspace/SCPDiscord_master/SCPDiscordBot/DiscordAPI.cs:line 109
   at SCPDiscord.NetworkSystem.Update() in /var/lib/jenkins/workspace/SCPDiscord_master/SCPDiscordBot/Network.cs:line 127
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
   ```

**Comment by SvatoYAngeL** [comment]
All rights have been granted properly

**Comment by KarlOfDuty** [comment]
Wait what, how old is the bot you are using? Send the entire log output from the bot.

**Comment by SvatoYAngeL** [comment]
```
[2025-01-06 05:23:06 -08:00] [500 /General     ] [Info ] Starting SCPDiscord version 2.0.6...
[2025-01-06 05:23:06 -08:00] [501 /Config      ] [Info ] Loading config "C:\Users\Administrator\Desktop\SCPDiscord\Bot\config.yml"
[2025-01-06 05:23:06 -08:00] [504 /Discord     ] [Info ] Setting up Discord client...
[2025-01-06 05:23:06] [504 /Discord     ] [Info ] Registering commands...
[2025-01-06 05:23:07] [504 /Discord     ] [Info ] Hooking events...
[2025-01-06 05:23:07] [504 /Discord     ] [Info ] Hooking command events...
[2025-01-06 05:23:07] [504 /Discord     ] [Info ] Connecting to Discord...
[2025-01-06 05:23:07] [101 /Startup     ] [Info ] DSharpPlus, version 4.3.0-nightly-01129
[2025-01-06 05:23:09] [502 /Network     ] [Info ] Listening on 127.0.0.1:6666
[2025-01-06 05:23:10] [504 /Discord     ] [Info ] Connected to Discord.
[2025-01-06 05:23:10] [502 /Network     ] [Info ] Plugin connected.
[2025-01-06 05:23:10] [104 /EventHandler] [Warn ] An event handler for READY took too long to execute. Defined as "OnReady(DSharpPlus.DiscordClient, DSharpPlus.EventArgs.ReadyEventArgs)" located in "SCPDiscord.DiscordAPI".
[2025-01-06 05:23:11] [504 /Discord     ] [Info ] Found Discord server: Teranii SCP
[2025-01-06 05:23:11] [502 /Network     ] [Warn ] Unknown packet received: { }
Unhandled exception. System.InvalidOperationException: Bots cannot use a custom status.
   at DSharpPlus.Entities.DiscordActivity..ctor(String name, ActivityType type)
   at SCPDiscord.DiscordAPI.SetActivity(String activityText, ActivityType activityType, UserStatus status) in /var/lib/jenkins/workspace/SCPDiscord_master/SCPDiscordBot/DiscordAPI.cs:line 109
   at SCPDiscord.NetworkSystem.Update() in /var/lib/jenkins/workspace/SCPDiscord_master/SCPDiscordBot/Network.cs:line 127
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

**Comment by KarlOfDuty** [comment]
How are things going?

**Comment by SvatoYAngeL** [comment]
Hello, I was able to solve the problem. I had to reinstall the config created by the terminal. it seemed to be just obsolete and different variables were on other lines

**Comment by KarlOfDuty** [comment]
Ok nice
